replicaCount: 1

image:
  repository: droken/ark-server-xvfb
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    - name: port1
      port: 50001
      targetPort: 50001
    - name: port2
      port: 50002
      targetPort: 50002
    - name: port3
      port: 50003
      targetPort: 50003

resources: {}


persistence:
  enabled: true
  hostPath: "/mnt/ark_data"
  size: 20Gi

config:
  steamcmd: /usr/games/.wine/drive_c/Steam
  env:
    PUID: "7777"
    PGID: "7777"
    BATTLEEYE: "FALSE"
    RCON_ENABLED: "TRUE"
    UPDATE_SERVER: "TRUE"
    ASA_PORT: "50001"
    RCON_PORT: "50002"
    MAX_PLAYERS: "70"
    CLUSTER_ID: "cluster"
    DISPLAY: ""
