image:
  repository: acekorneya/asa_server
  tag: latest
  pullPolicy: IfNotPresent

image:
  repository: scottyhardy/docker-wine
  tag: latest
  pullPolicy: IfNotPresent
  
resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  # Pas de limits pour éviter OOM kill (exit code 137)
  limits: {}

service:
  type: NodePort
  port: 7777
  queryPort: 27015
  rconPort: 27020
  nodePorts:
    port: 50001        # jeu
    queryPort: 50002   # query
    rconPort: 50003    # RCON

persistence:
  enabled: true
  storageClass: ""
  size: 20Gi
  mountPath: /arkserver/ShooterGame/Saved
  hostPath: /mnt/ark-backups

env:
  SERVER_NAME: "ARK NAS"
  MAP_NAME: "TheIsland"
  MAX_PLAYERS: "10"
  ADMIN_PASSWORD: "changeme"

# Désactivation des probes pour éviter restart en boucle
livenessProbe: null
readinessProbe: null
