image:
  repository: acekorneya/asa_server
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  # Pas de limits pour éviter OOM kill (exit code 137)
  limits: {}

service:
  type: NodePort
  port: 7777
  rconPort: 27020
  queryPort: 27015

persistence:
  enabled: true
  storageClass: ""
  size: 20Gi
  mountPath: /arkserver/ShooterGame/Saved
  hostPath: /mnt/ark-backups

env:
  SERVER_NAME: "ARK NAS"
  MAP_NAME: "TheIsland"
  MAX_PLAYERS: "10"
  ADMIN_PASSWORD: "changeme"

# Désactivation des probes pour éviter restart en boucle
livenessProbe: null
readinessProbe: null
