apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-data
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
