# ✅ values.yaml minimal (via Helm Chart)
server:
  name: ark-server
  map: Astraeos_WP
  sessionName: "ClubPing"
  serverPassword: ""
  serverAdminPassword: "MyPassword"
  customServerArgs: >-
    -Port=7777 -WinLiveMaxPlayers=70 -clusterid=cluster -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -MultiHome=88.184.158.243 -bRawSockets -UseBattlEye
  rcon:
    enabled: true
    port: 27020

service:
  type: NodePort
  gamePort:
    port: 7777
    nodePort: 50001
    protocol: UDP
  gamePortTCP:
    port: 7777
    nodePort: 50003
    protocol: TCP
  rcon:
    port: 27020
    nodePort: 50002
    protocol: TCP

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 4
    memory: 8Gi