# ✅ values.yaml minimal (via Helm Chart)
server:
  name: ark-server
  map: Astraeos_WP
  sessionName: "ClubPing"
  serverPassword: ""
  serverAdminPassword: "MyPassword"
  customServerArgs: >-
    -Port=7777 -WinLiveMaxPlayers=70 -clusterid=cluster -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -MultiHome=88.184.158.243 -bRawSockets -UseBattlEye
  rcon:
    enabled: true
    port: 27020

service:
  type: NodePort
  ports:
    gameUdp:
      port: 7777
      targetPort: game
      protocol: UDP
      nodePort: 50001
    gameTcp:
      port: 7777
      targetPort: 7777
      protocol: TCP
      nodePort: 50001
    rcon:
      port: 27020
      targetPort: 27020
      protocol: TCP
      nodePort: 50002


resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 4
    memory: 8Gi