# valeurs par défaut pour le chart ark-server

image:
  repository: acekorneya/asa_server
  tag: "2_1_latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "4"       # max 4 vCPU
    memory: "8Gi"  # max 8 Go RAM
  requests:
    cpu: "2"
    memory: "4Gi"

service:
  type: NodePort
  gameNodePort: 50001        # Port UDP exposé pour le jeu
  rconNodePort: 50002        # Port TCP exposé pour RCON

persistence:
  enabled: true
  hostPath: "/opt/arkserver"
  size: 50Gi
  storageClass: ""

serverConfig:
  sessionName: "ClubPing"
  mapName: "Astraeos"
  serverPassword: ""
  serverAdminPassword: "MyPassword"
  gamePort: 7777
  rconPort: 27020
  maxPlayers: 70
  clusterId: "cluster"
  modIds: ""
  passiveMods: ""
  customServerArgs: "-MultiHome=88.184.158.243 -bRawSockets"

monitoring:
  enabled: false
  serviceMonitor:
    interval: 15s
    port: "metrics"
