image:
  repository: acekorneya/asa_server
  tag: latest
  pullPolicy: IfNotPresent

ports:
  asa: 50001
  rcon: 50002

persistence:
  enabled: true
  path: /mnt/ark_data

resources:
  requests:
    cpu: "2"
    memory: "6Gi"
  limits:
    cpu: "4"
    memory: "12Gi"
