image:
  repository: acekorneya/asa_server
  tag: "2_1_latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"

service:
  type: LoadBalancer
  gamePort: 7777
  rconPort: 27020

persistence:
  enabled: true
  hostPath: "/opt/arkserver"
  size: 50Gi
  storageClass: ""

serverConfig:
  sessionName: "ClubPing"
  mapName: "Astraeos"
  serverPassword: ""
  serverAdminPassword: "MyPassword"
  gamePort: 7777
  rconPort: 27020
  maxPlayers: 70
  clusterId: "cluster"
  modIds: ""
  passiveMods: ""
  customServerArgs: "-MultiHome=192.168.0.240 -bRawSockets"

monitoring:
  enabled: false
