replicaCount: 1
image:
  repository: acekorneya/asa_server
  tag: latest

service:
  type: LoadBalancer
  port: 7777
  rconPort: 27020

persistence:
  size: 50Gi
  storageClassName: nfs-storage # ou hostpath

config:
  PUID: "7777"
  PGID: "7777"
  SESSION_NAME: "MonServeur"
  SERVER_ADMIN_PASSWORD: "Admin123"
backup:
  schedule: "0 3 * * *" # cron nightly

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15

prometheus:
  enabled: true
