# ============================================
# 🚀 ARK Server Helm Chart Values Configuration
# ============================================

image:
  repository: drokenhorisk/ark-server-xvfb
  tag: latest
  pullPolicy: IfNotPresent

serverConfig:
  serverName: ClubPing
  serverAdminPassword: MyPassword
  gamePort: 7777
  rconPort: 27020
  maxPlayers: 70
  map: Astraeos_WP
  clusterId: cluster
  multiHome: 88.184.158.243
  useBattleEye: true
  apiEnabled: false

service:
  type: NodePort
  ports:
    gameUDP:
      port: 7777
      nodePort: 50001
      protocol: UDP
    gameTCP:
      port: 7777
      protocol: TCP
    rcon:
      port: 27020
      nodePort: 50002
      protocol: TCP

persistence:
  enabled: true
  hostPath: /mnt/ark_data

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

monitoring:
  enabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 1200
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 1200
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
