# valeurs par défaut pour le chart ark-server

image:
  repository: acekorneya/asa_server
  tag: "2_1_latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "4"       # max 4 vCPU
    memory: "8Gi"  # max 8 Go RAM
  requests:
    cpu: "2"
    memory: "4Gi"

service:
  type: NodePort             # Type de Service (NodePort par défaut, peut être LoadBalancer)
  gameNodePort: 50001        # NodePort pour le port de jeu UDP (optionnel)
  rconNodePort: 50002        # NodePort pour le port RCON TCP (optionnel)

persistence:
  enabled: true
  hostPath: "/opt/arkserver"  # Chemin local pour stocker les données (par défaut sur le nœud)
  size: 50Gi                  # Taille du volume si on utilise une PVC
  storageClass: ""            # Classe de stockage si PVC (vide = défaut du cluster)

serverConfig:
  sessionName: "ClubPing"    # SESSION_NAME: nom de la session/du serveur
  mapName: "TheIsland"         # MAP_NAME: carte jouée (ex: "TheIsland")
  serverPassword: ""           # SERVER_PASSWORD: mot de passe pour rejoindre (vide si pas de mot de passe)
  serverAdminPassword: "MyPassword"  # SERVER_ADMIN_PASSWORD: mot de passe administrateur (RCON)
  gamePort: 7777               # ASA_PORT: port du jeu
  rconPort: 27020              # RCON_PORT: port du RCON (administration à distance)
  maxPlayers: 70               # MAX_PLAYERS: nombre max de joueurs
  clusterId: "cluster"         # CLUSTER_ID: identifiant de cluster pour les transferts
  modIds: ""                   # MOD_IDS: liste d'IDs de mods séparés par des virgules (si applicable)
  passiveMods: ""              # PASSIVE_MODS: mods "passifs" séparés par des virgules
  customServerArgs: ""         # CUSTOM_SERVER_ARGS: arguments additionnels au lancement (ex: "-ForceAllowCaveFlyers")

monitoring:
  enabled: false
  serviceMonitor:
    interval: 15s
    port: "metrics"
