apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ark-server
  namespace: argocd
spec:
  destination:
    namespace: ark-server
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/DrokenHorisk/ark-gitops.git
    targetRevision: HEAD
    path: charts/ark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
