apiVersion: batch/v1
kind: CronJob
metadata:
  name: ark-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            volumeMounts:
            - name: ark-data
              mountPath: /data
            command: ["sh","-c"]
            args:
              - tar czf /data/backups/backup-$(date +%Y%m%d%H%M).tgz /data
          restartPolicy: OnFailure
          volumes:
          - name: ark-data
            persistentVolumeClaim:
              claimName: ark-data
