apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ark-server.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "ark-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SERVER_ADMIN_PASSWORD: {{ .Values.serverConfig.serverAdminPassword | quote }}
  SERVER_PASSWORD: {{ .Values.serverConfig.serverPassword | quote }}
