apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ark-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ark-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: game
      port: {{ .Values.serverConfig.gamePort }}
      targetPort: game
      protocol: UDP
    - name: rcon
      port: {{ .Values.serverConfig.rconPort }}
      targetPort: rcon
      protocol: TCP
