apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ark-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ark-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: game-udp
    port: {{ .Values.serverConfig.gamePort }}
    protocol: UDP
    targetPort: game
    {{- if and (eq .Values.service.type "NodePort") .Values.service.gameNodePort }}
    nodePort: {{ .Values.service.gameNodePort }}
    {{- end }}
  - name: game-tcp
    port: {{ .Values.serverConfig.gamePort }}
    protocol: TCP
    targetPort: game-tcp
  - name: rcon
    port: {{ .Values.serverConfig.rconPort }}
    protocol: TCP
    targetPort: rcon
    {{- if and (eq .Values.service.type "NodePort") .Values.service.rconNodePort }}
    nodePort: {{ .Values.service.rconNodePort }}
    {{- end }}
