apiVersion: v1
kind: Service
metadata:
  name: ark-service
spec:
  type: LoadBalancer
  selector:
    app: ark-server
  ports:
    - name: asa
      protocol: TCP
      port: 50001
      targetPort: 50001
    - name: rcon
      protocol: TCP
      port: 50002
      targetPort: 50002
