apiVersion: v1
kind: Service
metadata:
  name: ark-service
spec:
  type: NodePort
  selector:
    app: ark-server
  spec:
  type: NodePort
  selector:
    app: ark-server
  ports:
    - name: asa
      port: 50001
      targetPort: 50001
      nodePort: 50001
    - name: rcon
      port: 50002
      targetPort: 50002
      nodePort: 50002

