# ✅ templates/service.yaml pour Helm
apiVersion: v1
kind: Service
metadata:
  name: ark-server-ark-server
  namespace: ark-server
  labels:
    app.kubernetes.io/name: ark-server
    app.kubernetes.io/instance: ark-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ark-server
    app.kubernetes.io/instance: ark-server
  ports:
    - name: game-udp
      protocol: UDP
      port: 7777
      targetPort: game
      nodePort: 50001
    - name: game-tcp
      protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 50001
    - name: rcon
      protocol: TCP
      port: 27020
      targetPort: 27020
      nodePort: 50002

