apiVersion: batch/v1
kind: CronJob
metadata:
  name: ark-backup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - tar czf /backups/ark-$(date +%Y%m%d-%H%M%S).tgz /arkdata
            volumeMounts:
              - name: ark-data
                mountPath: /arkdata
              - name: backup-vol
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: ark-data
              hostPath:
                path: /mnt/ark-backups
            - name: backup-vol
              hostPath:
                path: /mnt/ark-backups/snapshots
