apiVersion: batch/v1
kind: CronJob
metadata:
  name: ark-backup
  namespace: ark-server
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ark-backup
            image: busybox
            command: ["/bin/sh"]
            args: ["-c", "tar czf /backup/ark-backup-$(date +%F-%H-%M).tar.gz /ark/data"]
            volumeMounts:
              - name: ark-data
                mountPath: /ark/data
              - name: backup
                mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: ark-data
              persistentVolumeClaim:
                claimName: ark-data
            - name: backup
              hostPath:
                path: /mnt/backups/ark
                type: DirectoryOrCreate
