apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-asa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ark-asa
  template:
    metadata:
      labels:
        app: ark-asa
    spec:
      containers:
        - name: ark-asa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 50001
            - containerPort: 50002
            - containerPort: 50003
          env:
            {{- range $key, $value := .Values.config.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
              {{- end }}
          volumeMounts:
            - mountPath: /mnt/ark_data
              name: ark-data
      volumes:
        - name: ark-data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
