apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-server
  labels:
    app: ark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ark
  template:
    metadata:
      labels:
        app: ark
    spec:
      containers:
        - name: wine
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              Xvfb :0 &  # Lancer Xvfb pour simuler DISPLAY
              export DISPLAY=:0
              wineboot
              cd /home/wineuser
              wine /usr/games/ark/ASA.exe  # Adapter si le chemin est différent
          volumeMounts:
            - mountPath: /usr/games
              name: ark-data

          env:
            - name: SERVER_NAME
              value: {{ .Values.env.SERVER_NAME | quote }}
            - name: MAP_NAME
              value: {{ .Values.env.MAP_NAME | quote }}
            - name: MAX_PLAYERS
              value: {{ .Values.env.MAX_PLAYERS | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.env.ADMIN_PASSWORD | quote }}

          livenessProbe:
            exec:
              command:
                - pgrep
                - ShooterGameServer
            initialDelaySeconds: 120
            periodSeconds: 30

          # ❌ Readiness probe désactivée temporairement
          # readinessProbe:
          #   tcpSocket:
          #     port: 27020
          #   initialDelaySeconds: 60
          #   periodSeconds: 15

      volumes:
        - name: ark-data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
