apiVersion: v1
kind: Service
metadata:
  name: ark-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: ark-server
  ports:
    - port: {{ .Values.service.port }}
      protocol: UDP
      targetPort: {{ .Values.service.port }}
    - port: {{ .Values.service.rconPort }}
      protocol: TCP
      targetPort: {{ .Values.service.rconPort }}
