apiVersion: v1
kind: Service
metadata:
  name: ark-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ark
  ports:
    - name: gameport
      port: {{ .Values.service.port }}
      protocol: UDP
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePorts.gamePort }}
    - name: queryport
      port: {{ .Values.service.queryPort }}
      protocol: UDP
      targetPort: {{ .Values.service.queryPort }}
      nodePort: {{ .Values.service.nodePorts.queryPort }}
    - name: rconport
      port: {{ .Values.service.rconPort }}
      protocol: TCP
      targetPort: {{ .Values.service.rconPort }}
      nodePort: {{ .Values.service.nodePorts.rconPort }}
