apiVersion: v1
kind: Service
metadata:
  name: ark-asa
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ark-asa
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .port }}
      {{- end }}
