apiVersion: v1
kind: Service
metadata:
  name: ark-service
  namespace: ark-server
spec:
  selector:
    app: ark
  type: {{ .Values.service.type }}
  ports:
    - name: game
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
    - name: query
      port: {{ .Values.service.queryPort }}
      targetPort: {{ .Values.service.queryPort }}
      protocol: UDP
    - name: rcon
      port: {{ .Values.service.rconPort }}
      targetPort: {{ .Values.service.rconPort }}
      protocol: TCP
