apiVersion: v1
kind: Service
metadata:
  name: ark-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30777
    - port: 27015
      targetPort: 27015
      nodePort: 30715
    - port: 27020
      targetPort: 27020
      nodePort: 30720
  selector:
    app: ark
