apiVersion: v1
kind: Service
metadata:
  name: ark-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ark
  ports:
    - name: game
      protocol: {{ .Values.service.ports.game.protocol }}
      port: {{ .Values.service.ports.game.port }}
      targetPort: {{ .Values.service.ports.game.port }}
    - name: rcon
      protocol: {{ .Values.service.ports.rcon.protocol }}
      port: {{ .Values.service.ports.rcon.port }}
      targetPort: {{ .Values.service.ports.rcon.port }}
    - name: query
      protocol: {{ .Values.service.ports.query.protocol }}
      port: {{ .Values.service.ports.query.port }}
      targetPort: {{ .Values.service.ports.query.port }}
